name: Semantic Release

on:
  push:
    branch: [main]
  pull_request:
    branch: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with: 
          node-version: 18.13.0

      - name: Install Dependencies
        run: npm install

      - name: Build App
        run: npm build

      - name: Semantic Release
        env: 
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
